name: safenisa
description: Trying to replicate various app UIs in flutter


version: 3.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_floatactionbuttons: ^0.1.0
  flutter_spinkit: ^4.0.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2 
  firebase_database: ^4.1.1
  image_picker: ^0.6.3+1
  cloud_firestore: 
  animator: ^2.0.1
  bottomreveal: ^1.0.0
  cached_network_image: ^2.2.0+1
  charts_flutter: ^0.9.0
  crop: ^0.1.2
  firebase_storage: 
  flare_flutter: ^1.8.3
  flutter_custom_clippers: ^1.1.1
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  intro_views_flutter: ^2.8.1
  fluttertoast: ^7.1.1
  share: ^0.6.4+3
  google_maps_flutter: ^1.0.3
  geolocator: ^6.1.1
  http: ^0.12.2
  provider: ^4.3.2+2
  shared_preferences: ^0.5.6+1
  google_fonts: ^1.1.1
  flutter_feather_icons: ^1.0.3
  url_launcher: ^5.5.0
  rflutter_alert: ^1.1.0
  audioplayers: ^0.16.2
  flutter_audio_recorder: ^0.5.5
  path_provider: ^1.6.24
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_automation: null
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/app-store-logo.jpg"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/smwallet/
    - assets/hotel/
    - assets/icon/
    - assets/flare/

    - lib/src/pages/blog/
    - lib/src/pages/dialogs/
   
    - lib/src/pages/hotel/

    - lib/src/pages/misc/
    - lib/src/pages/quotes/
    - assets/nicasiaassets/
  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
